name: XCS234_A2
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.10
  - notebook=6.5.4
  - tk=8.6.12
  - ffmpeg=4.2.2
  - moviepy=1.0.3
  - scipy=1.10.1
  - tensorboard=2.12.1
  - pyyaml=6.0.1
  - pip=23.3
  - pip:
    - matplotlib==3.7.3
    - numpy==1.24.4
    - ale-py==0.8.1
    - pyglet==2.0.10
    - gym[atari]==0.26.2
    - autorom[accept-rom-license]==0.6.1
    - cmake==3.27.7; sys_platform != "win32"
    - wget==3.2; sys_platform != "win32"
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==2.1.0; sys_platform != "linux" and sys_platform != "win32"
    - torch==2.1.0+cpu; sys_platform == "linux" or sys_platform == "win32"
